apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service-clusterip
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-service
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service-loadbalancer
spec:
  ports:
    - name: 9091-8080
      port: 9091
      protocol: TCP
      targetPort: 8080
  selector:
    app: order-service
  type: LoadBalancer
status:
  loadBalancer: {}
